version: '3'
services:
  postgres:
    network_mode: 'bridge'
    container_name: postgres
    image: mdillon/postgis:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
